//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankingsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountsuboption
    {
        public int id { get; set; }
        public string accountsubject { get; set; }
        public string title { get; set; }
        public string optiontitle1 { get; set; }
        public string optiondesc1 { get; set; }
        public string optiontitle2 { get; set; }
        public string optiondesc2 { get; set; }
        public string optiontitle3 { get; set; }
        public string optiondesc3 { get; set; }
        public string accounttypename { get; set; }
    }
}
