//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankingsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountdetail
    {
        public int id { get; set; }
        public string title { get; set; }
        public string para1 { get; set; }
        public string para2 { get; set; }
        public string heading { get; set; }
        public string panel1title { get; set; }
        public string panel1subtitle1 { get; set; }
        public string panel1subtitle1content { get; set; }
        public string panel1subtitle2 { get; set; }
        public string panel1subtitle2content { get; set; }
        public string panel1subtitle3 { get; set; }
        public string panel1subtitle3content { get; set; }
        public string panel2title { get; set; }
        public string panel2subtitle1 { get; set; }
        public string panel2subtitle1content { get; set; }
        public string panel2subtitle2 { get; set; }
        public string panel2subtitle2content { get; set; }
        public string panel2subtitle3 { get; set; }
        public string panel2subtitle3content { get; set; }
        public string panel3title { get; set; }
        public string panel3subtitle1 { get; set; }
        public string panel3subtitle1content { get; set; }
        public string panel3subtitle2 { get; set; }
        public string panel3subtitle2content { get; set; }
        public string panel3subtitle3 { get; set; }
        public string panel3subtitle3content { get; set; }
        public string panel4title { get; set; }
        public string panel4subtitle1 { get; set; }
        public string panel4subtitle1content { get; set; }
        public string panel4subtitle2 { get; set; }
        public string panel4subtitle2content { get; set; }
        public string panel4subtitle3 { get; set; }
        public string panel4subtitle3content { get; set; }
        public string panel5title { get; set; }
        public string panel5subtitle1 { get; set; }
        public string panel5subtitle1content { get; set; }
        public string panel5subtitle2 { get; set; }
        public string panel5subtitle2content { get; set; }
        public string panel5subtitle3 { get; set; }
        public string panel5subtitle3content { get; set; }
        public string panel6title { get; set; }
        public string panel6subtitle1 { get; set; }
        public string panel6subtitle1content { get; set; }
        public string panel6subtitle2 { get; set; }
        public string panel6subtitle2content { get; set; }
        public string panel6subtitle3 { get; set; }
        public string panel6subtitle3content { get; set; }
        public string type { get; set; }
    }
}
