//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankingsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class beneficiary
    {
        public int id { get; set; }
        public string name { get; set; }
        public string nickname { get; set; }
        public string accountnumber { get; set; }
        public string ifsccode { get; set; }
        public string maxamount { get; set; }
        public string maxtransactions { get; set; }
        public string address { get; set; }
        public string usersaccountnumber { get; set; }
    }
}
