//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankingsystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eBankingEntities : DbContext
    {
        public eBankingEntities()
            : base("name=eBankingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<beneficiary> beneficiaries { get; set; }
        public DbSet<checkbook> checkbooks { get; set; }
        public DbSet<bankservice> bankservices { get; set; }
        public DbSet<transaction> transactions { get; set; }
        public DbSet<faq> faqs { get; set; }
        public DbSet<account> accounts { get; set; }
        public DbSet<accountsuboption> accountsuboptions { get; set; }
        public DbSet<adminuser> adminusers { get; set; }
        public DbSet<accountdetail> accountdetails { get; set; }
        public DbSet<user> users { get; set; }
    }
}
