//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankingsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int id { get; set; }
        public string name { get; set; }
        public string nickname { get; set; }
        public string senderaccountnumber { get; set; }
        public string receiveraccountnumber { get; set; }
        public string ifsccode { get; set; }
        public Nullable<System.DateTime> transactiondate { get; set; }
        public string creditamount { get; set; }
        public string debitamount { get; set; }
        public string senderbalanceamount { get; set; }
        public string receiverbalanceamount { get; set; }
    }
}
