//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankingsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string transactionpassword { get; set; }
        public string holdername { get; set; }
        public string accountnumber { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string image { get; set; }
        public string contactnumber { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> lastlogin { get; set; }
        public string location { get; set; }
        public string gender { get; set; }
        public string dateofbirth { get; set; }
        public string accountbalance { get; set; }
        public string randomtext { get; set; }
    }
}
